WebApplication6/Components/NavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NewsSite.Domain.Abstract;
using NewsSite.WebUi.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsSite.WebUi.Components
{
    public class NavTagsViewComponent : ViewComponent
    {
        private IPostRepository repository;
        private int countArticle = 4;

        public NavTagsViewComponent(IPostRepository repo)
        {
            this.repository = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            SidePanelViewModel model = new SidePanelViewModel
            {
                Categories = repository.Categories.OrderByDescending(n => n.Name.Length).Select(x => x.Name),
                Posts = repository.Posts.OrderByDescending(p => p.DateChanged).Take(countArticle),
            };

            return View(model);
        }
    }
}

WebApplication6/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using NewsSite.Domain.Abstract;
using NewsSite.Domain.Entities;
using NewsSite.WebUi.Models;
using System.Diagnostics;
using NewsSite.Domain.Concrete;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Localization;
using System.Globalization;

namespace NewsSite.WebUi.Controllers
{
 
    public class PostController : Controller
    {

        public int pageSize = 4;
        private IPostRepository repository;
        private UserManager<User> _userManager;
        private Task<User> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        public PostController(IPostRepository repo, UserManager<User> userManager)
        {
            this.repository = repo;
            this._userManager = userManager;
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return RedirectToAction("List");
        }

        [HttpPost]
        public ViewResult Search(string text = "", int page = 1) //add comment
        {

            IEnumerable<Post> posts = repository.Posts.Where(p => p.Title.ToUpper().Contains(text.ToUpper()));

            if (posts.Count() == 0)
            {
                posts = repository.Posts.Where(p => p.Text.ToUpper().Contains(text.ToUpper()));

                //if (posts.Count() == 0)
                  //  posts = repository.Posts.Where(p => p.Comments.Where(comment => comment.Text.ToUpper().Contains(text.ToUpper()));

            }

            PostListViewModel model = new PostListViewModel
            {
                Posts = posts
             .OrderByDescending(post => post.DateChanged)
             .Skip((page - 1) * pageSize)
             .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = posts.Count(),

                },
                Ratings = repository.Ratings
            };
            return View("List", model);
        }

        public async Task<ViewResult> List(string category, int page = 1)
        {
            IEnumerable<Post> posts = repository.Posts
                .Where(p => category == null || category == p.Category.Name);

            User curentUser = await GetCurrentUserAsync();

            if (curentUser != null)           
                posts = posts.Where(p => ((p.Rating.Count() > 2) & p.ValueRating >= curentUser.MinimalToShow) || (p.Rating.Count() <= 2));
      
            PostListViewModel model = new PostListViewModel
            {
                Posts = posts.OrderByDescending(post => post.ValueRating).
                Skip((page - 1) * pageSize)
                .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = posts.Count()

                },
                CurrentCategory = category,

                Ratings = repository.Ratings

            };
            return View(model);
        }

        public async Task<IActionResult> ShowPost(int id = 1)
        {
            Post post = repository.Posts.Where(p => p.PostId == id).FirstOrDefault();

            if (post == null)
                return NotFound();

            User user = null;
            if (post != null)
            {
                user = await _userManager.FindByIdAsync(post.UserId);

                if (user == null)
                {
                    return NotFound();
                }
            }

            var currentUser = await GetCurrentUserAsync();
            string currentUserId = "";

            if (currentUser != null)
                currentUserId = currentUser.Id;

            PostViewModel model = new PostViewModel
            {
                Post = post,
                Comments = repository.Comments.Where(c => c.PostId == id),
                User = user,
                Users = _userManager.Users,
                Likes = repository.Likes,
                CurrentUserId = currentUserId,
            };

            return View(model);
        }

        private static int GetCountTags(string tag, Post p)
        {
            return p.PostTags.Count(a => a.Tag.Name == tag);
        }

        [HttpPost]
        public ActionResult AddComment(int? parentId, int postId, string UserId, string Text)
        {
            if (Text != null)
            {
                repository.AddComment(parentId, postId, UserId, Text);
            }
            else
            {
                TempData["Required field"] = "Required field";

            }

            return RedirectToAction("ShowPost", new { id = postId });
        }
        [HttpPost]
        public async Task<JsonResult> SetRating(int id, int value)
        {
            if (User.Identity.IsAuthenticated)
            {
                Post post = repository.Posts.Where(x => x.PostId == id).First();

                var curentUser = await GetCurrentUserAsync();

                repository.SetRating(id, post, curentUser, value);

                return Json(post.ValueRating.ToString());

            }

            return Json(null);
        }

        [HttpPost]
        public async Task<JsonResult> LikeThis(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Comment comment = repository.Comments.Where(x => x.Id == id).First();

                var curentUser = await GetCurrentUserAsync();
                repository.SetLike(id, comment, curentUser);

                return Json(comment.LikeCount.ToString());
            }

            return Json(null);
        }


    }
}

WebApplication6/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewsSite.Domain.Entities;
using NewsSite.WebUi.ViewModel;

namespace NewsSite.WebUi.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        readonly SignInManager<User> _signInManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;

            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
   
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                var allRoles = _roleManager.Roles.ToList();
  
                var addedRoles = roles.Except(userRoles);

                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index", "Users");
            }

            return NotFound();
        }
    }
}

WebApplication6/Views/Shared/UsersIndex.cshtml
@{
    Layout = "_Layout";
}

<table class="table">
    <tr>
        <th>Image</th>
        <th>Email</th>
        <th></th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>
                <img src="@Url.Content(@user.UrlImage)" class="fluid-profile" />
            </td>
            <td>@user.Email</td>
           
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="ChangePassword" asp-route-id="@user.Id">Сменить пароль</a>
                    <a class="btn btn-sm btn-success" asp-controller="Roles" asp-action="Edit" asp-route-userid="@user.Id">Права</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Удалить
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

WebApplication6/Views/Shared/_AdminLayout.cshtml
@{
    ViewData["Title"] = "AdminPanel";
    Layout = "_Layout";
}

<head>
    @*<environment include="Development">*@
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <link href="~/css/magicsuggest.css" rel="stylesheet" type="text/css">

        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.js"
                integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
                crossorigin="anonymous"></script>
        <script src="~/js/magicsuggest.js"></script>
        <script src="~/js/site.js"></script>
    @*</environment>*@
</head>


<body>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebApplication6/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Identity
@using NewsSite.Domain.Entities
@inject IViewLocalizer Localizer
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["Profile"]</title>

    @*<environment include="Staging,Production">*@
    <link rel="icon" type="image/png" href="~/favicon.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    <link href="~/lib/jquery-bar-rating/dist/themes/bars-reversed.css" rel="stylesheet" />
   
    @*</environment>*@
    @*<environment exclude="Development">
           // <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@

    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-action="List" asp-controller="Post" asp-route-category="">@Localizer["Header"]</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    @if (User.Identity.IsAuthenticated)
                    {

                        <a asp-controller="Manage" asp-action="Index" class="nav-link">@User.Identity.Name </a>

                        <form method="post" asp-controller="Account" asp-action="LogOff">
                            <button type="submit" class="btn btn-light btn-sm">
                                <span class="fa fa-sign-out"></span> @Localizer["Exit"]
                            </button>
                        </form>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Login" class="nav-link">@Localizer["Login"]</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Register" class="nav-link">@Localizer["Register"]</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="Main">
        <div class="container">
            <div class="row">
                <div id="posts" class="col-lg-8">
                    @RenderBody()
                </div>
                <div id="tags" class="col-lg-4">
                    @await Component.InvokeAsync("NavTags")
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="py-3 bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">

                </div>
                <div class="col-lg-4 ">
                    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
                </div>
                <div class="col-lg-4">
                    <div class="float-right">
                        @await Html.PartialAsync("_SelectLanguagePartial")
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @*<environment include="Development">*@

        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@

        <script src="~/lib/jquery-bar-rating/jquery.barrating.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/js/site.js"></script>
    @*</environment>*@
    <environment exclude="Development">

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-bar-rating/jquery.barrating.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
      
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication6/Views/Shared/_ManageNav.cshtml
@using NewsSite.WebUi.Models.ManageViewModels
@using NewsSite.Domain.Entities
@using Microsoft.AspNetCore.Identity
@using NewsSite.Views.Manage
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject SignInManager<User> SignInManager

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a asp-action="Index" asp-controller="Manage" class="@ManageNavPages.IndexNavClass(ViewContext)">@Localizer["Profile"]</a>
    </li>
    <li class="nav-item">
        <a asp-action="UserArticles" asp-controller="Manage"
           class="@ManageNavPages.IndexListPost(ViewContext)">@Localizer["Articles"]</a>
    </li>
    <li class="nav-item">
        <a asp-action="ChangePassword" asp-controller="Manage"
           class="@ManageNavPages.ChangePasswordNavClass(ViewContext)">@Localizer["Password"]</a>
    </li>

    @if (User.IsInRole("admin"))
    {
        <li class="nav-item">
            <a asp-action="Index" asp-controller="Users" class="@ManageNavPages.IndexAllUsers(ViewContext)">@Localizer["List of users"]</a>
        </li>
        <li class="nav-item">
            <a asp-action="Index" asp-controller="Roles" class="nav-link">@Localizer["Roles"]</a>
        </li>
    }

</ul>

WebApplication6/Views/Shared/_PostSummary.cshtml
@model NewsSite.WebUi.ViewModel.PostSummaryViewModel
@using NewsSite.Domain.Entities;
@using NewsSite.WebUi.HtmlHelpers;
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Identity
@inject IViewLocalizer Localizer
@inject UserManager<User> UserManager


@{
    string userId = UserManager.GetUserId(User);
}

<div class="card mb-4">
    <div class="fill-logo">
        <img src="@Url.Content(Model.Post.Path)">
        <div class="card-body">
            <h2 class="card-title">@Model.Post.Title</h2>

            <p class="card-text">@Model.Post.Description</p>
            <p>
                @foreach (var item in @Model.Post.PostTags.Select(e => e.Tag))
                {
                    <div class="badge badge-dark">
                        @item.Name.ToUpper()
                    </div>
                }
            </p>
            <a asp-controller="Post" asp-action="ShowPost" asp-route-Id="@Model.Post.PostId" class="btn btn-primary"> @Localizer["Read More"] &rarr; </a>

        </div>
        <div class="card-footer text-muted">
            @Localizer["Posted on"] @Model.Post.DateChanged.ToString("f")
            <div class="float-right">
                <select id="rating-@Model.Post.PostId">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

    $(function () {

        var idRating = '#rating-@Model.Post.PostId';

        $(idRating).barrating({

            theme: 'bars-reversed',
            onSelect: function (value, text, event) {
                if (typeof (event) !== 'undefined') {
                    $.post("/Post/SetRating", { id: parseInt(@Model.Post.PostId), value: value }, function (data) {
                        $(idRating).barrating('readonly', true);
                        $(idRating).barrating('set', data);
                    });
                }
            },
            readonly: true,
            initialRating: @Model.Post.ValueRating,
        });

        @if (User.Identity.IsAuthenticated & Model.Ratings.Where(r=>r.UserId==userId).Count() == 0)
        {
            @:$(idRating).barrating('readonly', false);
        }
        });
</script>

WebApplication6/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{

    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocOptions.Value.SupportedCultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<form asp-controller="Post" asp-action="SetLanguage" method="post" class="">

    <select class="form-control form-control-sm" name="culture" onchange="this.form.submit();"
            asp-for="@requestCulture.RequestCulture.UICulture.Name"
            asp-items="cultureItems"></select>

</form>